### ISSUE TITLE
Add links from faculty load tab to other things?

### ISSUE THREAD

**Issue by rpruim** [senior-knights/course-schedulizer#110]
It would be nice if you could do things like click on an instructors name on the load table and jump to the faculty schedule tab with that faculty member focused.

Clicking on a course might jump to that course in the room view or it could jump to the faculty schedule view with the appropriate term selected.  (Have to think more about which is more useful.)

This is relatively low priority, but would increase the efficiency of using the app.

**Comment by rpruim** [comment]
As we mentioned on the call, this could be a way to give edit access to things that don't show up on the other views.  I'd suggest that as a good use for links here.

**Comment by rpruim** [comment]
Since it sounds like this is nearly done, I'll make it high priority -- Always nice to finish a high priority goal ;-)

**Comment by charkour** [comment]
Thanks!
