### ISSUE TITLE
Edit from Teaching Loads Tab

### ISSUE THREAD

**Issue by Jdellis818** [senior-knights/course-schedulizer#117]

**Comment by charkour** [comment]
Closing this issue because it is a duplicate of #141, but 141 has a description from @kvlinden and will be closed on PR #130

**Comment by charkour** [comment]
At least, I think it's a duplicate. Can be reopened if I'm wrong.

**Comment by kvlinden** [comment]
I thought that this was was to support editing of courses on the teaching loads tab?

**Comment by charkour** [comment]
Confirmed with @Jonri2, this is a duplicate. Thanks!
