### ISSUE TITLE
Time stamp last change for each section?

### ISSUE THREAD

**Issue by rpruim** [senior-knights/course-schedulizer#119]
I'm wondering if it would be useful to add an additional column that keeps track of the last change to a section.  Ideally this would only update when there is an actual change, not each time the section is "updated".

This can be useful for keeping track of changes -- it would be easy to filter by date to get recent changes.

For now I'm imagining that we would only store the time stamp -- we can use external tools to do the filtering.

**Comment by rpruim** [comment]
I’m tempted to move this to high since I think it will be super easy (famous last words) and useful for seeing the evolution of a schedule.

**Comment by charkour** [comment]
I think this feature could have some major implications to the workflow and understanding of the app. Before we work on this, we should discuss the feature set and requirements.

**Comment by Jdellis818** [comment]
Is this something that would only be viewable in the exported spreadsheet or also in the app?

**Comment by charkour** [comment]
Also, when importing a spreadsheet, you would you expect to see the time stamp?

**Comment by rpruim** [comment]
It could be missing on upload.  Missing values could either be left missing or populated with the current date/time.

For now I was thinking only to have it available in the export, but I could imagine ways to use it in the app as well (highlighting most recent changes, for example.)
