### ISSUE TITLE
Courses with multiple rooms only take the 1st room

### ISSUE THREAD

**Issue by Jdellis818** [senior-knights/course-schedulizer#138]
Importing a spreadsheet that has courses with multiple rooms separated with new lines results in just 1 room assigned. (e.g. HH 334\nHH 336 -> HH 334).

**Comment by kvlinden** [comment]
See: #139 
Both rooms for DATA 101 B showed up on the schedule.

**Comment by Jdellis818** [comment]
Duplicate of #139
