### ISSUE TITLE
Fix non-teaching activity load hour handling.

### ISSUE THREAD

**Issue by kvlinden** [senior-knights/course-schedulizer#142]
There's a bug that messes up the non-teaching load hours. If you:
1. Create a new non-teaching activity (e.g., Dept-Chair, 7 hours). This displays properly in the teaching-loads pane.
2. Export to draft. This saves the entry properly at the end of the CSV.
3. Import the saved draft. Now, the chair entry is gone.

The one-hour non-teaching activities seem to be working fine.

**Comment by kvlinden** [comment]
After further investigation, the export of non-teaching activities is affected by whether or not I specify the semester for the activity. E.g., a department chair activity, for which there is no semester, gets exported without some CSV columns, which messes up the import. 

If I export and then edit the CSV to line up the columns (e.g., to make sure that teaching load and faculty name get put in the right columns), then I get the activity on import. But the hours on the imported activities are all reset to 1. 

It looks like we need to make sure that non-teaching activities get dumped with all the same columns in the same order, mostly with blank entries (",,") but with important columns filled in (load hours, faculty name, semester (if there), name/description) with appropriately-formatted values.

**Comment by charkour** [comment]
Thanks for investigating the problem! We'll get someone assigned to it and working on it soon.

**Comment by kvlinden** [comment]
I'm not certain how much code has changed here, but after further investigation, it appears that:
1. all non-teaching activities by any faculty member will have the number of hours specified for the first activity read from the CSV.
2. only the first non-teaching activity from the CSV is shown on the teaching loads page.
3. exporting a schedule now produces properly formatted CSV entries, but assigns the total hours of all the activities to each of the activities.
