### ISSUE TITLE
Section entry bugs

### ISSUE THREAD

**Issue by bryantgeorge** [senior-knights/course-schedulizer#167]
This is very high priority!

1. From #159, @Jonri2 noticed that: "After testing a bit, I did uncover a fairly major issue. A section is no longer able to update or be added if the section letter is changed. So, if I open an existing section and change the letter to something new, then click on either "Update Section" or "Add New Section," nothing happens." Turns out this is in `develop` as well. After a bit of debugging, the issue is that the updated section letter isn't even sent to `addSectionToSchedule()`.
2. Making a non-teaching load with multiple teachers makes a new row in the table, like:
![image](https://user-images.githubusercontent.com/51130302/112473088-4cc1e480-8d44-11eb-8f98-fd2d35144499.png)
3. If you enter a new prefix, and you don't press enter, it creates undefined values (validation no longer ensures there is a prefix):
![image](https://user-images.githubusercontent.com/51130302/112473645-fd2fe880-8d44-11eb-9229-d65f4f3d1d21.png)

(Related to number 3, removing all instructors from a course, removes it from the room schedule even though it should still appear there, correct?)

**Comment by Jdellis818** [comment]
2 and 3 were definitely caused by #162. The validation should be an easy fix. I accidentally put `.required()` inside of the `array()` instead of outside

**Comment by bryantgeorge** [comment]
> 2 and 3 were definitely caused by #162. The validation should be an easy fix. I accidentally put `.required()` inside of the `array()` instead of outside

Yeah, that one seems easy (the error message also needed to be added to the griditemautocomplete)
