### ISSUE TITLE
Multi-room/time course entry support is limited.

### ISSUE THREAD

**Issue by kvlinden** [senior-knights/course-schedulizer#201]
The system has incomplete support for courses with multiple "lines" in the CSV, that is, courses with more than one time or room (e.g., CS 262: MW 1:30-2:20 NH 253 & F 1:30-3:20 SB 354).

It can import, edit, export in these course "lines". But it cannot add them.

**Comment by rpruim** [comment]
If we adopt the new daily schedule, this will be even more common since many 4-hour courses will meet 3 days per week for different lengths of time on different days.

**Comment by rpruim** [comment]
Except for the time field, this could be implemented in the current editing box by supporting delimiters and using R-style recycling.  For the time field, we would need to change back to a text-entry area or come up with some other interface.

Regarding delimiters: We probably want at least two.  Something like:

* `&`: multiple entries are always in effect (two instructors, two rooms, etc.)
*  `|`: alternating entries.  

Example: Prof A & Prof B; M | T R;   8:30 | 8:05. could code a 4-hour course with the current draft schedule with 2 instructors (who teach all 3 days).

**Comment by das43** [comment]
We discovered this functionality is in fact built-in, but you have to go about it in a tricky way.
If we want a class like CS262 to be in SB010 M/W and the lab on Friday:

First create the class as normal in the SB 010 room and ONLY SELECT Monday and Wednesday. It should appear on the schedule. 

Then click on the class to open up the editor window, change the room, and change the day to now only having friday selected. Click the Add New Section button.

It should now export with that class as 1 line on the spreadsheet with 2 sets of days, 2 sets of times, and 2 rooms.

Note, these are now treated as "blocks" so if you edit and use the Update Section button on the M/W part of the class the Friday will remain unaffected and vice versa.
