### ISSUE TITLE
Add ability to check for classes at "non-standard" times

### ISSUE THREAD

**Issue by rpruim** [senior-knights/course-schedulizer#240]
This could be especially useful in the first year of our new daily schedule.

**Comment by rpruim** [comment]
At the chairs meeting, this was a requested feature that I think many chairs would like.

**Comment by rpruim** [comment]
It occurs to me that you might not know what the standard times are.  Here you go:

[Class Schedule Template 2023-2024 (10-7-22).xlsx](https://github.com/senior-knights/course-schedulizer/files/10045575/Class.Schedule.Template.2023-2024.10-7-22.xlsx)

**Comment by rpruim** [comment]
Assuming I transcribed things correctly, here are the available standard times for scheduling:

```
{
"times": [
  {"day": ["M", "W", "F"], 
   "time": ["8:00", "9:15", "11:00", "12:15", "13:30", "14:45"],
   "duration": [65]},

  {"day": ["M", "W", "F"], 
   "time": ["8:15", "9:15", "11:00", "12:30", "13:30", "14:45"],
   "duration": [50]},

  {"day": ["T", "R"], 
   "time": ["8:00", "10:20", "12:15", "14:10"],
   "duration": [100]},

  {"day": ["T", "R"], 
   "time": ["8:30", "11:00", "12:30", "14:10"],
   "duration": [50]},
  
  {"day": ["M", "T", "R"], 
   "time": ["18:30"],
   "duration": [210, 100, 90, 65, 50]},

  {"day": ["M", "T", "W", "R", "F"], 
   "time": ["8:00", "9:30", "11:00", "13:00", "14:30", "16:00", "18:30"],
   "duration": [80]},

  {"day": ["M", "T", "W", "R", "F"], 
   "time": ["8:00", "11:15", "14:30", "18:30"],
   "duration": [170]},

  {"day": ["M", "T", "W", "R", "F"], 
   "time": ["8:00", "12:30", "18:30"],
   "duration": [180]},

  {"day": ["M", "T", "W", "R", "F"], 
   "time": ["8:00", "11:00", "13:30", "18:30"],
   "duration": [120]}
  ]
}
```

Use the cross product of day/time/duration (so all combinations of day, time and duration).  So the last comb gives 5 * 4 * 1 = 20 different available slots.

**Comment by rpruim** [comment]
And here is another way to view the data:

```
      day                  start                   duration       
--------------- --------------------------- ----------------------
    M, W, F      8:00, 9:15, 11:00, 12:15,            65          
                       13:30, 14:45                               

    M, W, F      8:15, 9:15, 11:00, 12:30,            50          
                       13:30, 14:45                               

     T, R        8:00, 10:20, 12:15, 14:10           100          

     T, R        8:30, 11:00, 12:30, 14:10            50          

    M, T, R                18:30             50, 65, 90, 100, 210 

 M, T, W, R, F             8:00               80, 120, 170, 180   

 M, T, W, R, F   8:00, 9:30, 11:00, 13:00,            80          
                    14:30, 16:00, 18:30                           

 M, T, W, R, F   8:00, 11:15, 14:30, 18:30           170          

 M, T, W, R, F      8:00, 12:30, 18:30               180          

 M, T, W, R, F   8:00, 11:00, 13:30, 18:30           120          
------------------------------------------------------------------
```

**Comment by rpruim** [comment]
Well, I think the standard times are shifting a bit (as of a meeting this morning), and may shift again (I just made a suggested change).  In any case, the JSON above is most likely not going to be correct.  Here is a new draft (with my proposed change incorporated -- we'll see if that makes the cut ;-).  I'll keep you posted as things get finalized.  Fortunately, if you build something out using the JSON format, it is easy to change the times just by updating a JSON file.

```
{
"times": [
  {"day": ["M", "W", "F"], 
   "time": ["8:00", "9:15", "11:00", "12:15", "13:30", "14:45"],
   "duration": [50, 65]},

  {"day": ["T", "R"], 
   "time": ["8:00", "10:20", "12:15", "14:10"],
   "duration": [50, 100]},

  {"day": ["T", "R"], 
   "time": ["8:55", "11:15", "13:10", "14:15"],
   "duration": [50]},
  
  {"day": ["M", "T", "R"], 
   "time": ["18:30"],
   "duration": [210, 100, 90, 65, 50]},

  {"day": ["M", "T", "W", "R", "F"], 
   "time": ["8:00"],
   "duration": [80, 120, 170, 180]},

  {"day": ["M", "T", "W", "R", "F"], 
   "time": ["8:00", "9:30", "11:00", "13:00", "14:30", "16:00", "18:30"],
   "duration": [80]},

  {"day": ["M", "T", "W", "R", "F"], 
   "time": ["8:00", "11:15", "14:30", "18:30"],
   "duration": [170]},

  {"day": ["M", "T", "W", "R", "F"], 
   "time": ["8:00", "12:30", "18:30"],
   "duration": [180]},

  {"day": ["M", "T", "W", "R", "F"], 
   "time": ["8:00", "11:00", "13:30", "18:30"],
   "duration": [120]}

]
}
```

```
------------------------------------------------------------------
      day                  time                    duration       
--------------- --------------------------- ----------------------
    M, W, F      8:00, 9:15, 11:00, 12:15,          50, 65        
                       13:30, 14:45                               

     T, R        8:00, 10:20, 12:15, 14:10         50, 100        

     T, R        8:55, 11:15, 13:10, 14:15            50          

    M, T, R                18:30             210, 100, 90, 65, 50 

 M, T, W, R, F             8:00               80, 120, 170, 180   

 M, T, W, R, F   8:00, 9:30, 11:00, 13:00,            80          
                    14:30, 16:00, 18:30                           

 M, T, W, R, F   8:00, 11:15, 14:30, 18:30           170          

 M, T, W, R, F      8:00, 12:30, 18:30               180          

 M, T, W, R, F   8:00, 11:00, 13:30, 18:30           120          
------------------------------------------------------------------
```

**Comment by rpruim** [comment]
My proposal was accepted.  So (for now, at least), the times above are the standard times.

**Comment by rpruim** [comment]
Here's another bit of data listing all the allowed times, including some additional things like times for music rehearsals.

[Class Schedule Meeting Patterns (2023-2024).xlsx](https://github.com/senior-knights/course-schedulizer/files/10077194/Class.Schedule.Meeting.Patterns.2023-2024.xlsx)

I have a query out to see if we can get data listing every course and its "type".  If so, we can do a finer check of the schedule that includes this information without asking chairs to enter it for every section.

**Comment by rpruim** [comment]
I'm going to close this since we have a PR (#296) that provides a workable solution.

We can open up additional issues for improvements to how this is done.

**Comment by charkour** [comment]
@rpruim, did you intend to close this? Just wanting to clean up the repo! Thanks.

**Comment by rpruim** [comment]
Yep.  This is working as (currently) intended.

The current solution will flag any meeting pattern unless it does one of two things

* uses all of the slots for a pattern
* uses exactly one slot from a pattern

That seems to be reasonable way to go, at least for now.

Right now the meeting pattern issues are flagged with an orange border (as opposed to red).  Perhaps those colors are too similar, but the first person who saw one of these did email me with a subject of "weird colors", so at least one other person can see the difference ;-)
