### ISSUE TITLE
Round all computed numeric output in the app.

### ISSUE THREAD

**Issue by rpruim** [senior-knights/course-schedulizer#252]
![image](https://user-images.githubusercontent.com/722231/199324129-3fec6e61-e04b-41cb-93ce-f1abcdee67c4.png)

Hopefully this is a pretty easy thing to fix.

**Comment by rpruim** [comment]
Here is a larger view of the output above:

![image](https://user-images.githubusercontent.com/722231/204578594-e8ac2e06-c467-4176-9383-e0825fd5b2ac.png)

**Comment by charkour** [comment]
Just throw a Math.round() call before saving the calculation and you should be good to go.
