### ISSUE TITLE
Bug: Import from reports.calvin.edu data is not picking up some of the columns correctly.

### ISSUE THREAD

**Issue by rpruim** [senior-knights/course-schedulizer#303]
[Course Section Report (3).csv](https://github.com/senior-knights/course-schedulizer/files/10116762/Course.Section.Report.3.csv)

I'm not sure when we introduced this bug, and I thought we had unit tests to check, but apparently we don't and I didn't notice the problem.

Currently if you import one of these files (example attached), it will only show up in the faculty loads section because the duration and days of week are missing (among other things).

**Comment by rpruim** [comment]
Turns out the bug was at CIT -- the data export was introducing spurious new line characters that misaligned the data for meeting patterns.

This has been fixed and imports are once again working as desired.

It sounds like the breaking change happened shortly before Thanksgiving.

**Comment by charkour** [comment]
Coordinating breaking software changes is rough...

**Comment by rpruim** [comment]
Yes, and we had no way to test against it because any test would have been using a data snapshot from when the data exported correctly :-/

To test this we would need to be able to log into the server that downloads the data and then have the app import it... Probably too complicated for us to automate at this point.
