### ISSUE TITLE
More than 1 room section when there are multiple professors

### ISSUE THREAD

**Issue by Jdellis818** [senior-knights/course-schedulizer#48]

**Comment by bryantgeorge** [comment]
#50 should serve as a good model for how to handle this issue with instructors separated by `"\n"` being for different meetings, but instructors separated by other delimiters (`";"`, `","`, etc.) being for the same meeting, so for example `"Bob Smith;Jane Doe\nGeorge Bryant"` would mean that Bob and Jane teach one meeting together while George teaches another meeting himself. This means that the instructors field should probably be moved to the meeting interface, and unfortunately this will mean that this issue will require code changes in a lot of places (parsing, exporting, rendering?, adding courses/sections/meetings).
