### ISSUE TITLE
Change requested on #62

### ISSUE THREAD

**Issue by charkour** [senior-knights/course-schedulizer#65]
Since we wanted to merge in #62 for the demo, here are changes requested that should be addressed.

* add `? moment(values?.meeting.startTime, "h:mm A").format("HH:mm")` there the `h:mm A` is the change when dealing with time. [link](https://github.com/senior-knights/course-schedulizer/pull/62#discussion_r532836599)
* [Fix the space given for location](https://github.com/senior-knights/course-schedulizer/pull/62#discussion_r532842834)
* [Turn the cusor to a hand when it is over an event](https://github.com/senior-knights/course-schedulizer/pull/62#issuecomment-735991218)
* ~~[generalize use of time](https://github.com/senior-knights/course-schedulizer/pull/62#issuecomment-736094772)~~ I believe this works properly in #58 
* Location and term is not respected when updating an event

Also, I suggested refactoring the popup button to another component, but I was thinking it might be better to make it a Higher Order Component to reuse and apply that logic. So that will be in a different PR.

**Comment by bryantgeorge** [comment]
Note to self: update should always delete the section being updated?
