### ISSUE TITLE
Revise Import Format

### ISSUE THREAD

**Issue by bryantgeorge** [senior-knights/course-schedulizer#81]
See https://github.com/senior-knights/course-schedulizer/issues/80

We probably should support importing these formats. Best to wait on this issue until we know more about the situation.

**Comment by charkour** [comment]
Is this issue (#81) closed by the PR #85?

**Comment by bryantgeorge** [comment]
> Is this issue (#81) closed by the PR #85?

Mostly, but we still don't have non-teaching import, correct?

**Comment by charkour** [comment]
Oh yes that is correct.
