### ISSUE TITLE
Add Excel Document Support for import. 

### ISSUE THREAD

**Issue by charkour** [senior-knights/course-schedulizer#87]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to convert the `.xlsx` to `.csv`.

**Describe the solution you'd like**
Ability to update a `.xlsx` file. 

**Describe alternatives you've considered**
I have considered using a program to convert `.xlsx` to `.csv`.

**Additional context**
Recommend using `xlsx` package on npm.

**Comment by bryantgeorge** [comment]
Is this primarily for import, or should we worry about this for export as well?

**Comment by charkour** [comment]
This one is for import. We can make another issue for output.
