### ISSUE TITLE
Reduce Amount of Scrolling

### ISSUE THREAD

**Issue by bryantgeorge** [senior-knights/course-schedulizer#88]
**Is your feature request related to a problem? Please describe.**
There is a lot of scrolling require to see everything currently.

**Describe the solution you'd like**
Reduce screen real-estate used and/or create another tab focused on visualizing at a wider view.

**Additional context**
See Pruim's original schedulizer for potential inspiration.

**Comment by charkour** [comment]
Remove the style that sets the width of one calendar to `24vw` and replace it with something that doesn't depend on view width.

**Comment by kvlinden** [comment]
Related to this, it's troublesome to edit the features of a section, save them, and then get dropped back on the schedule page fully reset. This requires the user to scroll back over to where they were editing.

**Comment by bryantgeorge** [comment]
> Related to this, it's troublesome to edit the features of a section, save them, and then get dropped back on the schedule page fully reset. This requires the user to scroll back over to where they were editing.

I think this will be addressed in #93
