### ISSUE TITLE
Import CSV through URL

### ISSUE THREAD

**Issue by bryantgeorge** [senior-knights/course-schedulizer#92]

**Comment by rpruim** [comment]
If the URL for the CSV doesn't produce a valid schedule, what should the response be?  It would be nice if the user got some feedback about whether the file simply couldn't be found or could be found but had some other error.

**Comment by charkour** [comment]
That's a good question. Clearly we didn't specify what the feedback would be, but there will be a modal this displays necessary feedback. We will implement this in #146
