### ISSUE TITLE
Jump to Added Section

### ISSUE THREAD

**Issue by bryantgeorge** [senior-knights/course-schedulizer#93]
From Pruim's Feedback:

**Is your feature request related to a problem? Please describe.**
Navigation is a little bit clunky. After editing or adding a section, the page refreshes.  That makes sense since the data have changed.

**Describe the solution you'd like**
But it would be nice if the view were focused on something related to the edit just made (ie. jump to and highlight (?) the section just added/updated).

**Comment by charkour** [comment]
Not sure what the best way to do this is, but react-virtualized I believe has a jump-to feature. If we use that package, it would optimize the rendering as well. 

Probably other packages that do what we want.
